---
abstract: 'Perl extension for direct-to-lpd printing.'
author:
  - 'Christopher M. Fuhrman <cfuhrman@panix.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Printer
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Net-Printer
  license: https://github.com/cfuhrman/net-printer/raw/master/LICENSE
  repository: https://github.com/cfuhrman/net-printer
version: 1.12
